/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Fruit: typeof import('./src/entities/Fruit')['Fruit']
  const Ground: typeof import('./src/entities/Ground')['Ground']
  const Plant: typeof import('./src/entities/Plant')['Plant']
  const Stats: typeof import('./src/entities/Stats')['Stats']
}
