/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Age: typeof import('../other/super-simple-js-game-engine/src/composition/Age')['Age']
  const Fruit: typeof import('./src/entities/Fruit')['Fruit']
  const GameEngine: typeof import('../other/super-simple-js-game-engine/src/GameEngine')['GameEngine']
  const Ground: typeof import('./src/entities/Ground')['Ground']
  const Plant: typeof import('./src/entities/Plant')['Plant']
  const Position: typeof import('../other/super-simple-js-game-engine/src/composition/Position')['Position']
  const Size: typeof import('../other/super-simple-js-game-engine/src/composition/Size')['Size']
  const State: typeof import('../other/super-simple-js-game-engine/src/composition/State')['State']
  const Stats: typeof import('./src/entities/Stats')['Stats']
}
